spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/db2022
    username: gaussdb
    password: Password@123
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl